data:
  datasets:
    train:
      - libribrain_speech_simplified:
          data_path: '<DATA_PATH>'
          preprocessing_str: 'bads+headpos+sss+notch+bp+ds'
          standardize: true
          tmin: 0.0
          tmax: 0.5
          exclude_run_keys: [['0', '11', 'Sherlock1', '2'], ['0', '12', 'Sherlock1', '2']]
          preload_files: false
          
    val:
      - libribrain_speech_simplified:
          data_path: '<DATA_PATH>'
          standardize: true
          tmin: 0.0
          tmax: 0.5
          include_run_keys: [['0', '11', 'Sherlock1', '2']]
          preload_files: false
    test:
      - libribrain_speech_simplified:
          data_path: '<DATA_PATH>'
          standardize: true
          tmin: 0.0
          tmax: 0.5
          include_run_keys: [['0', '12', 'Sherlock1', '2']]
          preload_files: false
  dataloader: 
    batch_size: 256
    num_workers: 4
  general:
    inMemory: False
    train_fraction: 1.0


model:
  - conv1d:
      in_channels: 306
      out_channels: 128
      kernel_size: 7
      stride: 1
      padding: 'same'
  - resnet_block:
      model_config:
        - elu:
        - conv1d:
            in_channels: 128
            out_channels: 128
            kernel_size: 3
            stride: 1
            padding: 'same'
        - elu:
        - conv1d:
            in_channels: 128
            out_channels: 128
            kernel_size: 1
            stride: 1
            padding: 'same'
  - elu:
  - conv1d:
      in_channels: 128
      out_channels: 128
      kernel_size: 50
      stride: 25
  - elu:
  - conv1d:
      in_channels: 128
      out_channels: 128
      kernel_size: 7
      stride: 1
      padding: 'same'
  - elu:
  - conv1d:
      in_channels: 128
      out_channels: 512
      kernel_size: 4
      padding: 0
  - relu:
  - dropout:
      p: 0.5
  - conv1d:
      in_channels: 512
      out_channels: 2
      kernel_size: 1
      padding: 0
  - flatten:

loss:
  name: cross_entropy
  
  
optimizer:
  name: adam
  config:
    lr: 0.0003
    
trainer:
  max_epochs: 20

general:
  wandb: True
  output_path: '<RESULTS_PATH>/final-speech-scaling'
  checkpoint_path: '<CHECKPOINTS_PATH>/final-speech-scaling'
  seed: 42